// Route paths
export const ROUTES = {
  LOGIN: '/login',
  REGISTER: '/register',
  DASHBOARD: '/',
  USERS: '/users',
  PROVIDERS: '/providers',
  REGISTRATIONS: '/registrations',
  REVIEWS: '/reviews',
  CATEGORIES: '/categories',
  PRODUCTS: '/products',
  REPORTS: '/reports',
  WARNINGS: '/warnings',
  BANNERS: '/banners',
  SPONSORSHIPS: '/sponsorships',
  OFFERS: '/offers',
  BADGES: '/badges',
  CHAT_MODERATION: '/chat-moderation',
  ANALYTICS: '/analytics',
  ADMIN_USERS: '/admin-users',
  AUDIT_LOG: '/audit-log',
  SETTINGS: '/settings',
  NOTIFICATIONS: '/notifications',
  BUG_REPORTS: '/bug-reports-admin',
  CREATE_USER: '/create-user',
  CREATE_PROVIDER: '/create-provider',
  PHOTO_MODERATION: '/photo-moderation',
  FEATURE_FLAGS: '/feature-flags',
  MODERATION_QUEUE: '/moderation-queue',
  VOUCHERS: '/vouchers',
  SUBSCRIPTIONS: '/subscriptions',
  PAYMENTS: '/payments',
  REVENUE: '/revenue',
  MONETIZATION_SETTINGS: '/monetization-settings',
};

export const API_BASE_URL = import.meta.env.VITE_API_URL || 'https://p8lfvsk0-3001.inc1.devtunnels.ms/api/';
